---
- name: Configure Router-on-a-Stick sur R1
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Reload interface physiques
      cisco.ios.ios_config:
        lines:
          - no ip address
          - duplex full
          - speed 100
          - no shutdown
        parents: "interface {{ item }}"
      loop:
        - FastEthernet0/1
        - FastEthernet1/0

    # Configuration des sub-interfaces (Data + Management)
    - name: 1.1 - Configurer les sous-interfaces
      cisco.ios.ios_config:
        parents: "interface {{ item.phy }}.{{ item.vlan }}"
        lines:
          - encapsulation dot1q {{ item.vlan }}
          - ip address {{ item.ip }} {{ item.mask }}
          - no shutdown
      loop: "{{ router_subifs }}"