---
- name: Configure VLANs et ports sur les switches
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Forcer la configuration physique du Trunk
      cisco.ios.ios_config:
        lines:
          - duplex full
          - speed 1000
        parents: "interface {{ switches_config[inventory_hostname].trunk_port }}"
      vars:
        ansible_command_timeout: 90

    # Création des VLANs (
    - name: Créer les VLANs
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ item.id }}"
            name: "{{ item.name }}"
            state: active
      loop: "{{ vlans_switches }}"
    
    # Configuration des ports utilisateurs
    - name: Configurer les ports ACCESS
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: access
            access:
              vlan: "{{ item.vlan }}"
      loop: "{{ switches_config[inventory_hostname].access_ports }}"

    # Configuration du Trunk 
    - name: 3.1 - Configurer le mode TRUNK
      cisco.ios.ios_config:
        parents: "interface {{ switches_config[inventory_hostname].trunk_port }}"
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport trunk native vlan 1
          - switchport trunk allowed vlan 1,10,20,30,40,99,100
          - no shutdown
      vars:
        ansible_command_timeout: 90